language: c
group: travis_stable
sudo: required

env:
  global:
    - PAGER=cat

matrix:
  include:
    - env: PGSQL_VERSION=10 POSTGIS_VERSION=2.4

before_install:
  - sudo bash $TRAVIS_BUILD_DIR/scripts/ci/install_postgres.sh
  - sudo make clean-all

install:
  - sudo make install

script:
  - cd src/pg
  - make test || { cat $TRAVIS_BUILD_DIR/src/pg/test/regression.diffs; false; }
