language: c

env:
  global:
    - PAGER=cat

before_install:
  - sudo add-apt-repository -y ppa:cartodb/postgresql-9.5
  - sudo add-apt-repository -y ppa:cartodb/gis
  - sudo add-apt-repository -y ppa:cartodb/gis-testing
  - sudo apt-get update

  # Install postgres db and build deps
  - sudo /etc/init.d/postgresql stop # stop travis default instance
  - sudo apt-get -y remove --purge postgresql-9.1
  - sudo apt-get -y remove --purge postgresql-9.2
  - sudo apt-get -y remove --purge postgresql-9.3
  - sudo apt-get -y remove --purge postgresql-9.4
  - sudo apt-get -y remove --purge postgresql-9.5
  - sudo rm -rf /var/lib/postgresql/
  - sudo rm -rf /var/log/postgresql/
  - sudo rm -rf /etc/postgresql/
  - sudo apt-get -y remove --purge postgis-2.2
  - sudo apt-get -y autoremove

  - sudo apt-get -y install postgresql-9.5=9.5.2-3cdb3
  - sudo apt-get -y install postgresql-server-dev-9.5=9.5.2-3cdb3
  - sudo apt-get -y install postgresql-plpython-9.5=9.5.2-3cdb3
  - sudo apt-get -y install postgresql-9.5-postgis-scripts=2.2.2.0-cdb2
  - sudo apt-get -y install postgresql-9.5-postgis-2.2=2.2.2.0-cdb2

  # configure it to accept local connections from postgres
  - echo -e "# TYPE  DATABASE        USER            ADDRESS                 METHOD \nlocal   all             postgres                                trust\nlocal   all             all                                     trust\nhost    all             all             127.0.0.1/32            trust" \
    | sudo tee /etc/postgresql/9.5/main/pg_hba.conf
  - sudo /etc/init.d/postgresql restart 9.5

install:
  - sudo make install

script:
  - cd src/pg
  - make test || { cat src/pg/test/regression.diffs; false; }
