language: generic
sudo: required
env:
  matrix:
    - DOCKER_IMAGE=carto/postgresql10:latest
    - DOCKER_IMAGE=carto/postgresql11:latest
services:
  - docker
before_install: docker pull ${DOCKER_IMAGE}
script:
  - ./scripts/ci/docker-test.sh ${DOCKER_IMAGE}
